[package]
edition = "2021"
name = "prime"
version = "0.1.0"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
crate-type = ["cdylib"]
name = "prime_standalone"
path = "src/prime.rs"

[dependencies]
num = "0.4.0"
wasm-bindgen = "0.2"
